# Generated by Django 2.1.5 on 2019-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('bio', models.TextField()),
                ('birthdate', models.DateField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('plot', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('actor', models.ManyToManyField(related_name='Actor', to='imdb.ActorList', verbose_name='ACTOR/ACTRESS')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
