# Generated by Django 2.1.5 on 2019-07-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='poster',
        ),
    ]
