# Generated by Django 2.1.5 on 2019-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
