# Generated by Django 2.1.5 on 2019-07-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
