# Generated by Django 2.1.5 on 2019-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_remove_movielist_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='poster',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
