# Generated by Django 2.1.5 on 2019-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
