# Generated by Django 2.1.5 on 2019-07-14 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20190714_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')]),
        ),
    ]
