# Generated by Django 2.1.5 on 2019-07-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_movielist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='image',
        ),
    ]
